# Sample .travis.yml for R projects

language: r
cran: http://cran.r-project.org/
warnings_are_errors: true
sudo: required

r_check_revdep: false
r_packages: 
  - dcemriS4
  - fmri
  - oro.dicom
  - covr
r_binary_packages: 
  - RCurl
  - testthat
  - XML
apt_packages:
 - libcurl4-openssl-dev
 - libxml2-dev

r_build_args: --compact-vignettes=gs+qpdf --resave-data
r_check_args: --as-cran

notifications:
  email:
    on_success: change
    on_failure: change

after_deploy:
  # travis_wait 100 Rscript -e 'covr::coveralls(type = "all")' ;
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; 
    then
      Rscript -e 'covr::coveralls(type = "all")' ;
    fi
