# Sample .travis.yml for R projects

language: r
cran: http://cran.r-project.org/
warnings_are_errors: true
sudo: false
cache: packages

r_check_revdep: false
os:
  - linux
  - osx
  

r_build_args: --compact-vignettes=gs+qpdf --resave-data
r_check_args: "--as-cran --install-args=--build"


notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; 
    then
      Rscript -e 'covr::coveralls(type = "all")' ;
    fi
